config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'home#index'

  devise_for :users
  get 'home/index'

  resources :pets do
    get 'routes'
    get 'new_route'
    get 'show_route'
  end
  resources :walks, :tracks, :locations
  
  resources :users do
  	get 'walker', :on => :collection
  	post 'hire_walker', :on => :collection
  end
end

app/models/pet.rb
# == Schema Information
#
# Table name: pets
#
#  id         :integer          not null, primary key
#  name       :string
#  num_chip   :string
#  born_date  :datetime
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  race       :string
#  avatar     :string
#

class Pet < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader

  # associations
  belongs_to :user, inverse_of: :pets
  #belongs_to :race, inverse_of: :pet
  has_many :walks, inverse_of: :pet, dependent: :destroy

  # validations
  validates :name, :born_date, presence: true
  validates :num_chip, presence: true, uniqueness: true
  validates_processing_of :avatar
  validate :avatar_size_validation

  private
	  def avatar_size_validation
	    errors[:avatar] << t('activerecord.attributes.errors.models.pet.attributes.avatar') if avatar.size > 0.5.megabytes
	  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  PER_PAGE = 10

  def index
    @own_pets = Pet.where(user_id: current_user.id).order('name ASC').page(params[:page]).per(PER_PAGE)

    @onwer_hire_walker = User.where(walker: current_user.id)
    #if @onwer_hire_walker.present?
      @walkered_pets = []
      @onwer_hire_walker.each do |owner| 
        pets = Pet.where(user_id: owner.id).order('name ASC').page(params[:page]).per(PER_PAGE)
        pets.each do |pet|
          @walkered_pets << pet
        end
      end
    #else
    #  my_walks = Walk.where(walker: current_user.id)
    #end
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user_id = current_user.id if current_user
     
    if @pet.save
      flash[:success] = t('activerecord.attributes.pet.confirmation')
      redirect_to @pet
    else
      render 'new'
    end
  end

  def update
    @pet = Pet.find(params[:id])
 
    # if params[:pet][:remove_avatar] == '1' 
    #   @pet.remove_avatar!
    #   @pet.save
    # end
    if @pet.update(pet_params)
      redirect_to @pet
    else
      render 'edit'
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
 
    redirect_to pets_path
  end

  def routes
    @pet_id = params[:pet_id].to_i
    @pet_name = Pet.find(@pet_id).name
    @actual_time = Time.now.strftime('%H:%M:%S')

    @walk_in_process = Walk.where("pet_id = #{@pet_id} AND state = 0")
    if @walk_in_process.present? 
      @state = 0
      @points_locations = get_locations_in_process(@walk_in_process, @actual_time, @state)

      @account_points_locations = @points_locations.count
      @last_point = @points_locations.last if @points_locations.present?
      @coordinates = get_last_point_track(@walk_in_process, @state)

      unless @last_point.nil?
        @last_point_at_moment = get_last_point_at_moment(@last_point) 
        update_walk_in_process(@walk_in_process, @state, @account_points_locations, @last_point, @coordinates, @last_point_at_moment)
      end

      @duration = @last_point_track.timer unless @last_point_track.nil?
      if @duration.to_date == Time.now.to_date
        if (@duration.strftime('%H:%M:%S') < @actual_time) && (@last_point - @coordinates == [])
          @walk_in_process[0].state = 1
          @walk_in_process[0].last_data_received = @last_point_at_moment.timer
          @walk_in_process[0].duration = Time.at(@account_points_locations * 5).utc.strftime("%H:%M:%S") #@duration.strftime("%H:%M:%S") 
          @walk_in_process[0].save!
          @state = 1
          Rails.logger.info "____________________"
          Rails.logger.info @walk_in_process[0].state
          Rails.logger.info @walk_in_process[0].last_data_received
          Rails.logger.info @walk_in_process[0].duration
          Rails.logger.info "____________________"
        end 
      end unless @duration.nil?
    else
      @finished_walks = Walk.where("pet_id = #{@pet_id} AND state = 1").to_a
      @finished_walk = @finished_walks.max_by(&:id)
      if @finished_walk.present?
        @points_locations = get_locations_finalized(@finished_walk, @actual_time, 1)
        @last_point = @points_locations.last

        @state = 1
      else
        @location_gran_canaria = Location.create(latitude: 28.127222, longitude: -15.431389)
        @last_point = @location_gran_canaria
        @points_locations = [[@last_point.latitude, @last_point.longitude]]

        @state = 1
      end
    end

    @last_point_at_moment = get_last_point_at_moment(@last_point) unless @last_point.nil?

    @hash_map = Gmaps4rails.build_markers(@last_point_at_moment) do |location, marker|
      marker.lat location.latitude  
      marker.lng location.longitude  
    end

    # @hash_map_last_point = Hash.new
    # @hash_map_last_point[:lat] = @last_point_at_moment[0]
    # @hash_map_last_point[:lng] = @last_point_at_moment[1]
    # @hash_last_point = []
    # @hash_last_point << @hash_map_last_point

    unless @walk_in_process[0].nil?
      @walk_id = @finished_walk.present? ? @finished_walk.id : @walk_in_process[0].id
    end

    if current_user.is_walker.nil?
      @walker_current_user = User.where(walker: current_user.walker)
      @pet_current_user = Pet.where(user_id: current_user.walker).map(&:id)
    else
      @walker_current_user = User.where(walker: current_user.id)
      @pet_current_user = Pet.where(user_id: current_user.hired).map(&:id)
    end

    unless @walker_current_user.blank?
      @walker_current_user = @walker_current_user[0].id
      @pet_walker = Pet.where(user_id: @walker_current_user) 
    else
      @pet_walker = []
    end

    @walks = Walk.where(pet_id: @pet_id).order('created_at DESC').page(params[:page]).per(PER_PAGE)
    respond_to do |format| 
      format.html
      format.json { render json: { points_locations: @points_locations, state: @state, walk_id: @walk_id, walks: @walks, pet_id: @pet_id, pet_current_user: @pet_current_user } }
    end
  end

  def new_route
    @pet_id = params[:pet_id].to_i
    
    name_last_walk = Walk.where(pet_id: @pet_id).last
    if name_last_walk.nil? 
      num_walk = "0"
    else
      name_last_walk = name_last_walk.name
      num_walk = name_last_walk.partition('_').last unless name_last_walk.nil?
    end
    num_walk = num_walk.to_i + 1
    name_route = "Ruta_" + "#{num_walk}"
    
    @walk = Walk.create
    @walk.pet_id = @pet_id
    @walk.walker = current_user.id
    @walk.name = name_route 
    @walk.state = "in_progress"
    @walk.save!
    
    # pets = Pet.where(user_id: @pet_id.user_id)
    # pets = pets.map(&:id)
    # pets.each do |pet|
    #   walks = Walk.where(pet_id: pet.id)
    #   if walks[0].state == "in_progress"
    #     track_another_pet = Track.where(walk_id: walks[0].id)
    #     @track = Track.create
    #     @track.file_name = track_another_pet[0].file_name
    #     @track.walk_id = @walk.id
    #     @track.save!
    #     break
    #   end
    # end

    prng = Random.new
    num_file = prng.rand(10)
    @file = Nokogiri::XML(File.open("extra/kml_files/doc1-#{num_file}.kml"))
    
    @track = Track.create
    @track.file_name = "doc1-#{num_file}"
    @track.walk_id = @walk.id
    @track.save!

    first_time = 0
    
    @file.css('coordinates').each do |coordinates|
      coordinates.text.split(' ').each do |coordinate|
        (lat, lon, elevation) = coordinate.split(',')
        @location = Location.create
        @location.track_id = @track.id     
        @location.latitude = lat
        @location.longitude = lon
        Rails.logger.info "-----------------"
        Rails.logger.info @location
        Rails.logger.info "-----------------"
        if first_time == 0
          @time_without_seconds = Time.now
          @location.timer = @time_without_seconds
          @time_plus_seconds = @time_without_seconds
          first_time = 1
          Rails.logger.info "**********************"
          Rails.logger.info @time_without_seconds
          Rails.logger.info @location.timer
          Rails.logger.info @time_plus_seconds
          Rails.logger.info "**********************"
        else
          @time_plus_seconds = @time_plus_seconds + 5.seconds
          @location.timer = @time_plus_seconds
          Rails.logger.info "++++++++++++++++++++++"
          Rails.logger.info @time_plus_seconds
          Rails.logger.info @location.timer
          Rails.logger.info "++++++++++++++++++++++"
        end
        @location.save!
        puts "#{lat},#{lon}\n"
      end
    end

    redirect_to pet_routes_path(@pet_id)
  end

  def show_route
    @pet_id = params[:pet_id].to_i
    @pet_name = Pet.find(@pet_id).name
    @walks = Walk.where(pet_id: @pet_id).order('created_at DESC').page(params[:page]).per(PER_PAGE)

    @actual_time = Time.now.strftime('%H:%M:%S')

    @walk_id = params[:walk_id].to_i
    @walk = Walk.find(@walk_id)
    if @walk.state == 'in_progress'
      redirect_to pet_routes_path(@pet_id)
    end
    @walk_name = @walk.name

    @points_locations = get_locations_finalized(@walk, @actual_time, 1)
    @last_point = @points_locations.last if @points_locations.present?

    unless @last_point.nil?
      @last_point_at_moment = get_last_point_at_moment(@last_point)
    end

    @hash_map = Gmaps4rails.build_markers(@last_point_at_moment) do |location, marker|
      marker.lat location.latitude  
      marker.lng location.longitude  
    end

    if current_user.is_walker.nil?
      @walker_current_user = User.where(walker: current_user.walker)
      @pet_current_user = Pet.where(user_id: current_user.walker).map(&:id)
    else
      @walker_current_user = User.where(walker: current_user.id)
      @pet_current_user = Pet.where(user_id: current_user.hired).map(&:id)
    end

    @state = 1
    @pet_walker = []
  end

  private
  def update_walk_in_process(walk_in_process, state, account_points_locations, last_point, coordinates, last_point_at_moment)
    @track_id = get_track_id(walk_in_process, state)
    duration_walk = Time.at(account_points_locations * 5).utc.strftime("%H:%M:%S")
    @walk_in_process[0].last_data_received = last_point_at_moment.timer
    @walk_in_process[0].duration = duration_walk
    @walk_in_process[0].state = (last_point - coordinates == []) ? 1 : 0
    @walk_in_process[0].save!
  end

  def get_last_point_track(walk_in_process, state)
    @track_id = get_track_id(walk_in_process, state)
    @last_point_track = Location.where(track_id: @track_id).last
    @coordinates = []
    @coordinates << @last_point_track.latitude 
    return @coordinates << @last_point_track.longitude
  end

  def get_last_point_at_moment(last_point)
    if last_point.is_a?(ActiveRecord::Base)
      last_point_latitude = last_point.latitude
      last_point_longitude = last_point.longitude
    else
      last_point_latitude = last_point[0]
      last_point_longitude = last_point[1]
    end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_calendar.html.erb
<script>
  var do_on_load = function(){

		$.datepicker.regional['es'] = {
			closeText: 'Cerrar',
			prevText: '<Ant',
			nextText: 'Sig>',
			currentText: 'Hoy',
			monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
			monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
			dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
			dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
			dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
			weekHeader: 'Sm',
			dateFormat: 'dd/mm/yy',
			firstDay: 1,
			isRTL: false,
			showMonthAfterYear: false,
			yearSuffix: ''
		};

		$.datepicker.setDefaults($.datepicker.regional['es']);

		$( "#datepicker" ).datepicker({
			dateFormat: "dd/mm/yy",
			showOn: "button",
      buttonImage: "http://jqueryui.com/resources/demos/datepicker/images/calendar.gif",
      //changeMonth: true,
			//changeYear: true,
      buttonImageOnly: true
		});

		$(".ui-datepicker-trigger").css({
    	'display': 'inline-block',
    	'padding-left': '5px'
  	});

	};

	$(document).ready(do_on_load)
	$(window).bind('page:change', do_on_load)
</script>

app/views/pets/_form.html.erb
<%= render "pets/calendar" %>
<%= form_for @pet do |f| %>
  <% if @pet.errors.any?%>
    <div id="error_explanation" >
     <h2>
        <%#= pluralize(@pet.errors.count, t('activerecord.attributes.pet.errors')) %> 
        <%= t('activerecord.attributes.pet.error') %>:
      </h2>
      <ul>
        <% @pet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', data: { required: true } %>
  </div>

  <div class="form-group">
    <%= f.label :num_chip %>
    <%= f.text_field :num_chip, class: 'form-control', data: { required: true } %>
  </div>  

  <div class="form-group">
    <%= f.label :born_date %>
    <% if request.url.include? "new" %>
      <%= f.text_field :born_date, id: 'datepicker', value: DateTime.now.strftime("%d/%m/%Y"), dataclass: 'form-control', data: { required: true } %>
    <% else %>
      <%= f.text_field :born_date, value: @pet.born_date.strftime("%d/%m/%Y"), id: 'datepicker', dataclass: 'form-control', data: { required: true } %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :race %><br>
    <%= f.select(:race, Race.all.map {|race| [race.name, race.name]}, {}, { class: 'form-control' }) %>
  </div> 
 
  <div class="form-group">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %><br>
    <% if f.object.avatar? %>
      <%= image_tag(@pet.avatar_url) if @pet.avatar? %><br>
      <%#= f.label :remove_avatar %>
      <%#= f.check_box(:remove_avatar, method: :delete, data: { confirm: (t 'activerecord.attributes.pet.sure') }) %> 
    <% end %>
  </div>
 
  <div class="form-group">
    <%= link_to (t('activerecord.attributes.pet.back')), pets_path, :class => 'button left' %>
    <%= f.submit "Enviar", :class => 'button right' %>
  </div>
<% end %>

app/views/pets/_list_walks.html.erb
<%= content_tag "div", class: "container" do %>
  <h2><%= t 'activerecord.attributes.walk.list' %></h2>
  <table class="table">
    <tr>
      <th><%= t 'activerecord.attributes.walk.name' %></th>
      <th><%= t 'activerecord.attributes.walk.created_at' %></th>
      <th><%= t 'activerecord.attributes.walk.duration' %></th>
      <th><%= t 'activerecord.attributes.walk.last_data_received' %></th>
      <th><%= t 'activerecord.attributes.walk.state' %></th>
      <% if current_user.role == 'owner' %>
        <th><%= t 'activerecord.attributes.walk.walker' %></th>
      <% end %>
      <th colspan="1"></th>
    </tr>

    <% unless @walks.nil? %>
      <% @walks.each do |walk| %>
        <tr id="walk-<%= walk.id %>">
          <td><%= link_to walk.name, {:controller => "pets", :action => "show_route", :walk_id => walk.id, :pet_id => @pet_id } %></td>
          <td><%= walk.created_at.strftime("%d/%m/%y %H:%M:%S") %></td>
          <td class="duration"><%= walk.duration.strftime("%H:%M:%S") %></td>
          <td class="data_received"><%= walk.last_data_received.strftime("%d/%m/%y %H:%M:%S") %></td>
          <td class="state"><%= t("activerecord.attributes.pet.#{walk.state}") %></td>
          <% if current_user.role == 'owner' %>
            <% name_walker = User.find(walk.walker).name %>
            <td><%= name_walker %></td>
          <% end%>
          <% if current_user.role == 'owner' %>
            <% if walk.state == 'finalized' %>
              <td><%= link_to (t 'activerecord.attributes.walk.delete'), walk_path(walk), 
                    method: :delete, 
                    data: { confirm: (t 'activerecord.attributes.pet.sure') } %></td>
            <% else %>    
              <td><%= (t 'activerecord.attributes.walk.delete') %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </table>
  <!--<div style="text-align: center;"><%#= paginate @walks, :theme => 'twitter-bootstrap-3' %></div> -->
<% end %>

app/views/pets/_map.html.erb
<% @walk_id = 0 if @walk_id == [] %>
<div id="map_<%= @walk_id %>" style='width: 600px; height: 400px; margin-top: 0.5cm; margin-left: 260px; display:inline-block;'></div>

<div style="float: right; padding: 163px 135px 1px 1px; ">
  <% @pets_user = Pet.where(user_id: current_user.id) %>
  <% @pets_user = @pets_user.map(&:id).include?(@pet_id) %>
  <!-- Si es el propietario o el estado de la ruta es en progreso se oculta el botón de Iniciar nueva ruta -->
  <% @actual_walk = Walk.where("pet_id = #{@pet_id} AND @state = 0") %>
  <% @class_init_route = (@pets_user == true || @actual_walk.present?) ? "hide" : "btn btn-default" %>
  <% @id_button = @state == 1 ? "" : "button_route" %>
  <%= button_to "Iniciar nueva ruta", pet_new_route_path, :class => @class_init_route, :id => @id_button, :method => :get %>
</div>

<script type="text/javascript">

$(document).ready(function () {

  function update_table(data) {
    var id = data.id;
    id = id.toString();
    var walk_id = 'walk-' + id;
    var duration_walk = '#' + walk_id + ' .duration';
    var data_received_walk = '#' + walk_id + ' .data_received';
    var state_walk = '#' + walk_id + ' .state';

    var duration = data.duration.substring(11, 19);
    $(duration_walk).text(duration);

    var last_data_received = new Date(data.last_data_received).toLocaleString();;
    $(data_received_walk).text(last_data_received);
    
    if (data.state == "in_progress") {
      var state = 'En progreso';
    }
    else {
      if (data.state == "finalized") {
        var state = 'Finalizado';
        $('#button_route').removeClass('hide');
        $('#button_route').addClass('btn btn-default');
      }
    }
    $(state_walk).text(state);
  }
  
  //function print_map(points_locations, state, hash_map) {
  function print_map(points_locations) {
    handler = Gmaps.build('Google');
    var mapOptions = { mapTypeId: google.maps.MapTypeId.HYBRID };
    handler.buildMap({ provider: mapOptions, internal: {id: 'map_<%= @walk_id %>'}}, function(){
      var plan = points_locations;
      plan.options = {
        geodesic: true,
        strokeColor: '#FF0000',
        strokeOpacity: 1.0,
        strokeWeight: 2,
        title: 'plan'
      };

      function addPolyline(polyline) {
        var transformedPolyline = _.map(polyline, function(coordinates) {
          return {
            lat: coordinates[0],
            lng: coordinates[1]
          };
        })
        handler.addPolyline(transformedPolyline, polyline.options);
        handler.bounds.extend(transformedPolyline[0]);
        handler.bounds.extend(polyline[polyline.length - 1]);
      }
      addPolyline(plan);
      
      if (<%= @state %> == 1) {
        markers = handler.addMarkers(<%= raw @hash_map.to_json %>);
        handler.map.centerOn(markers[0]); 
        handler.bounds.extendWith(markers); 

        handler.getMap().setZoom(15);
      }
      // else {
      //   if (state == 0 || state == 1) {
      //     markers = handler.addMarkers(hash_map);
      //   }
      // }  

      //handler.map.centerOn(markers[0]); 
      // to set the map zoom
      if (<%= @state %> != 1) {
        handler.getMap().setZoom(15); 
        handler.fitMapToBounds();
      }

      //handler.bounds.extendWith(markers);
      //handler.fitMapToBounds();
    });
  }

  function refreshData() {
    $.ajax({
      type: "GET",
      dataType: "json",
      url: '/pets/<%= @pet_id %>/routes',
      success: function(data) {
        update_table(data.walks[0]);
        print_map(data.points_locations);
        if (data.state == 1) {
          print_map(data.points_locations);//, data.state, data.hash_map);
          update_table(data.walks[0]);
          clearInterval(rm);
        }
      }
    })
  }

  // will call refreshPartial every 5 seconds
  if (<%= @state %> == 1) {
  	print_map(<%= @points_locations %>);
  }
  else {
    //if (<%#= @pet_current_user.include?(@pet_id) || @pet_walker.map(&:id).include?(@pet_id)
 //%>) {
      refreshData();
      var rm = setInterval(refreshData, 5000);  
   // }
  }

});
</script>

app/views/pets/edit.html.erb
<div class="authform">
	<h3><%= t('activerecord.attributes.pet.editing') %></h3>

	<%= render 'form' %>
</div>

app/views/pets/index.html.erb
<div class="container">
  <h2><%= t 'activerecord.attributes.pet.list' %></h2>

  <%= link_to t('activerecord.attributes.pet.new_pet'), new_pet_path %>

  <table class="table">
    <tr>
      <th><%= t 'activerecord.attributes.pet.avatar' %></th>
      <th><%= t 'activerecord.attributes.pet.name' %></th>
      <th><%= t 'activerecord.attributes.pet.num_chip' %></th>
      <th><%= t 'activerecord.attributes.pet.race' %></th>
      <th><%= t 'activerecord.attributes.pet.born_date' %></th>
      <th><%= t 'activerecord.attributes.pet.comment' %></th>
      <th colspan="3"></th>
    </tr>

    <% @own_pets.each do |pet| %>
      <tr>
        <td><%= image_tag pet.avatar.thumb.url %></td>
        <td><%= pet.name %></td>
        <td><%= pet.num_chip %></td>
        <td><%= pet.race %></td> 
        <td><%= pet.born_date.to_date.strftime("%d/%m/%Y") %></td>
        <td><%= pet.comment %></td>
        <td><%= link_to (t 'activerecord.attributes.pet.routes'), pet_routes_path(pet) %></td>
        <td><%= link_to (t 'activerecord.attributes.pet.edit'), edit_pet_path(pet) %></td>
        <td><%= link_to (t 'activerecord.attributes.pet.delete'), pet_path(pet),
                method: :delete,
                data: { confirm: (t 'activerecord.attributes.pet.sure') } %></td>
      </tr>
    <% end %>
  </table>
  <% unless @own_pets.nil? %>
    <div style="text-align: center;"><%= paginate @own_pets, :theme => 'twitter-bootstrap-3' %></div> 
  <% end %>
</div>

<% unless current_user.is_walker == "0" || current_user.is_walker.blank? %>
  <div class="container">
    <h2><%= t 'activerecord.attributes.pet.list_walker' %></h2>

    <table class="table">
      <tr>
        <th><%= t 'activerecord.attributes.pet.avatar' %></th>
        <th><%= t 'activerecord.attributes.pet.name' %></th>
        <th><%= t 'activerecord.attributes.pet.num_chip' %></th>
        <th><%= t 'activerecord.attributes.pet.race' %></th>
        <th><%= t 'activerecord.attributes.pet.born_date' %></th>
        <th><%= t 'activerecord.attributes.pet.comment' %></th>
        <th><%= t 'activerecord.attributes.pet.owner' %></th>
        <th colspan="1"></th>
      </tr>

      <% @walkered_pets.each do |pet| %>
        <tr>
          <td><%= image_tag pet.avatar.thumb.url %></td>
          <td><%= pet.name %></td>
          <td><%= pet.num_chip %></td>
          <td><%= pet.race %></td> 
          <td><%= pet.born_date.to_date.strftime("%d/%m/%Y") %></td>
          <td><%= pet.comment %></td>
          <% id_owner = Pet.find(pet.id).user_id
          name_owner = User.find(id_owner).name %>
          <td><%= name_owner %></td>
          <td><%= link_to (t 'activerecord.attributes.pet.routes'), pet_routes_path(pet) %></td>
        </tr>
       <% end unless @walkered_pets.nil? %>
    </table>
    <%# unless @walkered_pets.nil? %>
      <!--<div style="text-align: center;"><%#= paginate @walkered_pets, :theme => 'twitter-bootstrap-3' %></div>-->
    <%# end %>
  </div>
<% end %>

app/views/pets/new.html.erb
<div class="authform">
	<h3><%= t('activerecord.attributes.pet.new') %></h3>

	<%= render 'form' %>
</div>

app/views/pets/routes.html.erb
<div class="container"><h2 style="text-align: center;"><%= @pet_name%></h2>
	<%= render 'map' %>
	<%= render 'list_walks' %>
</div>

app/views/pets/show.html.erb
<div class="authform">
  <div class="form-group">
    <strong><%= t('activerecord.attributes.pet.avatar') %>:</strong>
    <%= image_tag @pet.avatar.thumb.url %>
  </div>

  <div class="form-group">
    <strong><%= t('activerecord.attributes.pet.name') %>:</strong>
    <%= @pet.name %>
  </div>

  <div class="form-group">
    <strong><%= t('activerecord.attributes.pet.num_chip') %>:</strong>
    <%= @pet.num_chip %>
  </div>

  <div class="form-group">
    <strong><%= t('activerecord.attributes.pet.born_date') %>:</strong>
    <%= @pet.born_date.strftime("%d/%m/%Y") %>
  </div>

  <div class="form-group">
    <strong><%= t('activerecord.attributes.pet.race') %>:</strong>
    <%= @pet.race %>
  </div> 

  <div class="form-group">
    <strong><%= t('activerecord.attributes.pet.comments') %>:</strong>
    <%= @pet.comment %>
  </div>

  <%= link_to (t('activerecord.attributes.pet.edit')), edit_pet_path(@pet), :class => 'button left' %> 
  <%= link_to (t('activerecord.attributes.pet.back')), pets_path, :class => 'button right' %>
</div>

app/views/pets/show_route.html.erb
<div class="container"><h2 style="text-align: center;"><%= @pet_name %></h2>
	<%= render 'map' %>
	<%= render 'list_walks' %>
</div>