config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'home#index'

  devise_for :users
  get 'home/index'

  resources :pets do
    get 'routes'
    get 'new_route'
    get 'show_route'
  end
  resources :walks, :tracks, :locations
  
  resources :users do
  	get 'walker', :on => :collection
  	post 'hire_walker', :on => :collection
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav">
        <li><%= link_to t('layouts.navigation.home'), root_path, class: 'navbar-brand' %></li>
      </ul>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
    <% if current_user.admin? %>
      <li><%= link_to t('layouts.navigation_links.users'), users_path %></li>
    <% end %>
  <% if current_user.owner? || current_user.walker? %>
    <li><%= link_to t('layouts.navigation_links.dogs'), pets_path %></li>
  	<li><%= link_to t('layouts.navigation_links.walkers'), walker_users_path %></li>
  <% end %>
  <% if current_user.walker? %>
    <li><%= link_to t('layouts.navigation_links.my_walks'), walks_path %></li>
  <% end %>
  <li><%= link_to current_user.name, edit_user_registration_path %></li>
  <li><%= link_to t('layouts.navigation_links.sign_out'), destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to t('layouts.navigation_links.sign_in'), new_user_session_path, class: 'navbar-nav' %></li>
  <li><%= link_to t('layouts.navigation_links.sign_up'), new_user_registration_path, class: 'navbar-nav' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GPS-PET" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "GPS-PET" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyDR5pZb3x_z86wNwysHQMISWDxiX1P_9eM"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>